### PR TITLE
Add actions before/after each section's output

### PR DESCRIPTION
**Pull request by banderon**

### CODE REVIEW

**Comment by prettyboymp** [comment]
@banderon what is the need here?  To print something above the section title?

**Comment by banderon** [comment]
@prettyboymp Correct. Using this on a number of sites, the default output doesn't provide for any separation between sections. This would allow adding a bit of space between them (or whatever styling is desired), as well as the ability to add ID output to link directly to a section via hash.

**Comment by prettyboymp** [comment]
If it's not an immediate need, I would prefer a patch submitted to core's trac to add the hooks there instead of copying an entire core function to just add two hooks.

**Comment by prettyboymp** [comment]
if it is an immediate need, do both.

**Comment by banderon** [comment]
Fair. I figured a patch on core would take months to years to make it in, whereas here it could be accomplished in a day.

**Pull request closed without merging**
