### PR TITLE
HTML escape option labels in dropdown display callback.

### PR DESCRIPTION
**Pull request by jeffstieler**
VIP feedback 2015-06-02

### CODE REVIEW

**Comment by prettyboymp** [comment]
ref #10

**Comment by prettyboymp** [comment]
I don't know of any off hand, but there may be cases where the label contains html.  I would say to go ahead with the merge for now, but we may have to switch to a `wp_kses_post()` filter instead of `esc_html()`.

**Comment by jeffstieler** [comment]
Thanks for the follow up @prettyboymp - I'll switch to `wp_kses_post()`.

**Comment by jeffstieler** [comment]
@prettyboymp scratch that - only text is allowed in `<option>` elements.  See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

**Pull request merged**
